In [1]:
import statsmodels.api as sm
from statsmodels.formula.api import ols
import numpy as np
import matplotlib.pyplot as plt
import csv
import pandas as pd
from pathlib import Path
import seaborn as sns
from datetime import date
from scipy import stats

#info and functions from here https://www.statology.org/two-way-anova-python/

In [3]:
today = date.today()
print("Today's date:", today)
date_today = str(today)
date_today

data_dir = Path.cwd() / 'Pearson Correlation data2022-01-13 ignoring non-MT pixels-using ALL DATA.csv'

df = pd.read_csv(str(data_dir))
df = df[df['[GFP-DCX](nM)']==0.5]

df = df.rename(columns = {'Pearson Coeff' : 'pearson', 
                    '[RFP-DCX](nM)': 'dcx_conc', 
                    'Type': 'mutant'})

df = df[['mutant', 'pearson', 'dcx_conc']]

df.head()

Today's date: 2022-01-13

   mutant   pearson  dcx_conc
11     WT  0.525376       8.5
12     WT  0.564458       8.5
13     WT  0.719327       8.5
14     WT  0.618079       8.5
15     WT  0.575891       8.5

In [4]:
#from here https://www.statology.org/two-way-anova-python/

model = ols('pearson ~ C(mutant) + C(dcx_conc) + C(mutant):C(dcx_conc)', data=df).fit()
results = sm.stats.anova_lm(model, typ=2)

# results['PR(>F)'] = np.round(results['PR(>F)'], 7)
results
# Since the p-values for water and sun are both less than .05, this means that both factors have a statistically significant effect on plant height.

                         sum_sq     df          F        PR(>F)
C(mutant)              0.366224    1.0  26.311829  9.881040e-07
C(dcx_conc)            0.062166    4.0   1.116602  3.513575e-01
C(mutant):C(dcx_conc)  0.157055    4.0   2.820945  2.751998e-02
Residual               1.879012  135.0        NaN           NaN

In [5]:
results.to_csv(Path.cwd() / f'{date_today} results of two-way anova.csv')